name: CI

on:
  push:
    branches:
    - master
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
        build-system: ["make", "tests/build-cmake.sh", "STANDARD=17 tests/build-cmake.sh"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install external dependencies with apt
      run: >-
        sudo apt-get update -y &&
        sudo apt-get install -y
        tree
        cmake
        libhdf5-serial-dev
        libboost-dev
        libeigen3-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install h5py pyyaml
        python -m pip list
    - name: Build
      run: ${{ matrix.build-system }}
    - name: Run tests
      run: |
        bash tests/test-highway.sh
        bash tests/test-GRU.sh
        bash tests/test-BatchNorm.sh
        bash tests/test-dense_dropout_functional.sh
        bash tests/test-lstm_functional.sh
        bash tests/test-merge-graph.sh
        bash tests/test-time-distributed-dense.sh
        bash tests/test-gru-sequence.sh
        bash tests/check-version-number.sh
        bash tests/check-conversion.sh
        bash tests/test-leaky-relu.sh
        bash tests/test-elu.sh
